module.exports = {
  EDIT: 'EDIT',
  EDIT_PRODUCT: 'EDIT_PRODUCT', //oc line
  NEW: 'NEW',
  NEW_PRODUCT: 'NEW_PRODUCT', //oc line
  NEW_RATING: 'NEW_RATING',
  RESULT: 'RESULT',
  RESULT_PRODUCT: 'RESULT_PRODUCT', //oc line
  RESULT_PAGE: 'RESULT_PAGE', //oc line
  ENTRY: 'ENTRY',
  PRODUCT: 'PRODUCT', //oc line
  INFO: 'INFO',
  EFFECTS_INFO: 'EFFECTS_INFO', //oc line
  CONTACT: 'CONTACT',
  EFFECTS_CONTACT: 'EFFECTS_CONTACT', //oc line
  MAP_INFO: 'MAP_INO',
  DONATE: 'DONATE',
  EFFECTS_CONTRIB: 'EFFECTS_CONTRIB', //oc line
  JOIN: 'JOIN',
  TEAM: 'TEAM',
  SUPPORTERS: 'SUPPORTERS',
  IMPRINT: 'IMPRINT',
  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  EMAIL_CONFIRMED: 'EMAIL_CONFIRMED',
  CONFIRM_EMAIL_ERROR:'CONFIRM_EMAIL_ERROR',
  CONFIRMING_EMAIL:'CONFIRMING_EMAIL',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  OPEN_SOURCE: 'OPEN_SOURCE',
  WAIT: 'WAIT',
  IO_ERROR: 'IO_ERROR',
  LOCATE: 'LOCATE',
  LOCATE_DISABLED: 'LOCATE_DISABLED',
  DONATE_FOR_EVENTS: 'DONATE_FOR_EVENTS',
  SUBSCRIBE_TO_BBOX: 'SUBSCRIBE_TO_BBOX',
};
